- src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
- src/main/java/bdbe/bdbd/user/OwnerRestController.java
- src/main/java/bdbe/bdbd/user/OwnerService.java
- src/main/java/bdbe/bdbd/user/User.java
- src/main/java/bdbe/bdbd/user/UserRequest.java
- src/main/java/bdbe/bdbd/user/UserResponse.java
- src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
- src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
로그인 및 회원가입 기능을 role을 분기로 사용자와 관리자로 나누어 시큐리티 및 서비스 구현
테스트는 성공 테스트 구현함. -> 차주에 실패 테스트 구현 예정
> feat: 유저 및 사용자 로그인 및 회원가입 기능 구현

- src/main/java/bdbe/bdbd/bay/Bay.java
- src/main/java/bdbe/bdbd/bay/BayJPARepository.java
- src/main/java/bdbe/bdbd/bay/BayRequest.java
- src/main/java/bdbe/bdbd/bay/BayResponse.java
- src/main/java/bdbe/bdbd/bay/BayRestController.java
- src/main/java/bdbe/bdbd/bay/BayService.java
> feat: 베이 기능 구현

- src/main/java/bdbe/bdbd/bay/BayRestController.java
- src/main/java/bdbe/bdbd/bay/BayService.java
- src/main/java/bdbe/bdbd/carwash/Carwash.java
- src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
- src/main/java/bdbe/bdbd/location/LocationJPARepository.java
- src/main/java/bdbe/bdbd/optime/Optime.java
- src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
- src/main/java/bdbe/bdbd/reservation/Reservation.java
- src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
- src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
- src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
- src/main/java/bdbe/bdbd/reservation/ReservationService.java
- src/main/java/bdbe/bdbd/review/ReviewRequest.java
- src/main/java/bdbe/bdbd/review/ReviewResponse.java
- src/main/java/bdbe/bdbd/review/ReviewRestController.java
- src/main/java/bdbe/bdbd/review/ReviewService.java
- src/main/java/bdbe/bdbd/user/UserJPARepository.java
- src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
- src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
- src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
- src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
- 추가적으로 고려해야할 부분에 대해 구현
- 버그가 존재하는(잘 작동되지 않는) 코드 고침
- 기능 구현
> refactor: 코드 작동되도록 리팩토링 및 버그 수정

- src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
- src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
- src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
- src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/file/File.java
권한 기반이 정상적으로 동작하게끔 수정하였습니다.
김용준 멘토님의 도움을 많이 받았습니다.
#1c28256
> fix: 시큐리티 권한 "ROLE_" 하드코딩 수정

- src/main/java/bdbe/bdbd/carwash/Carwash.java
- src/main/java/bdbe/bdbd/reservation/Reservation.java
- src/main/java/bdbe/bdbd/reservation/ReservationService.java
- src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
예약 entity 삭제가 아닌 논리적 삭제(is_deleted)로 수정하였습니다.
> refactor: 예약 취소 리팩토링

- src/main/java/bdbe/bdbd/carwash/Carwash.java
- src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/location/Location.java
- src/main/java/bdbe/bdbd/optime/Optime.java
- src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
feat: 세차장 정보 수정_ 기존 정보 불러오기 완료
feat: 세차장 정보 수정_ 상세 정보 수정 (optime, carwashKeyword 제외 -> 보완 예정)
> feat: 세차장 정보 수정 기능 

- src/main/java/bdbe/bdbd/_core/errors/utils/DateUtils.java
- src/main/java/bdbe/bdbd/_core/errors/utils/KeywordTypeConverter.java
- src/main/java/bdbe/bdbd/bay/BayJPARepository.java
- src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
- src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/keyword/Keyword.java
- src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
- src/main/java/bdbe/bdbd/keyword/KeywordType.java
- src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
- src/main/java/bdbe/bdbd/reservation/ReservationService.java
- src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
- src/main/java/bdbe/bdbd/review/ReviewResponse.java
- src/main/java/bdbe/bdbd/review/ReviewService.java
- src/main/java/bdbe/bdbd/user/OwnerResponse.java
- src/main/java/bdbe/bdbd/user/OwnerService.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
- src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
- src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
- src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
- 코드 리뷰 피드백 반영
- 프론트 api 요구사항 반영
- 세차장 정보 불러오기 버그 수정
> refactor: 코드 리뷰 피드백 반영 및 프론트 api 요구사항 반영

- src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
- src/main/java/bdbe/bdbd/location/Location.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
- 세차장 검색 기능 테스트 코드 에러 해결
- 세차장 수정 
- 버그 (운영시간, 키워드 부분 반영안됨) 해결 (새로운 로직 추가)
- 필요 없는 코드 삭제 
- 요청 dto, 응답 dto 분리
> fix: 세차장 수정 버그 제거 및 리팩토링

- src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
- src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
- src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/file/FileRequest.java
- src/main/java/bdbe/bdbd/file/FileResponse.java
- src/main/java/bdbe/bdbd/file/FileRestController.java
- src/main/java/bdbe/bdbd/file/FileService.java
- src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
- 파일 업로드 기능을 유틸리티로 분리 (캡슐화)하고 리팩토링
- 다중 파일 등록 기능 구현
- 세차장 등록 기능에 다중 파일 등록 기능 반영
> refactor: 파일 업로드 기능 리팩토링 및 세차장 등록에 반영

- src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
> refactor: AwsConfig 위치 변경

- src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/file/FileJPARepository.java
- src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
- src/main/java/bdbe/bdbd/reservation/ReservationService.java
- src/main/java/bdbe/bdbd/user/OwnerResponse.java
- src/main/java/bdbe/bdbd/user/OwnerService.java
Reverts Step3-kakao-tech-campus/Team10_BE#96
> Revert "feat: 이미지 업로드가 포함된 api 전체 반영"

- src/main/resources/application-dbtest.yml
Reverts Step3-kakao-tech-campus/Team10_BE#116
> Revert "delete: src/main/resources/application-dbtest.yml"

- src/main/java/bdbe/bdbd/bay/BayRestController.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/member/MemberRestController.java
- src/main/java/bdbe/bdbd/member/OwnerRestController.java
- src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
- src/main/java/bdbe/bdbd/review/ReviewRestController.java
- src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
- src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
- src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
- src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
- src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Reverts Step3-kakao-tech-campus/Team10_BE#120
> Revert "refactor: api 경로에 /api 추가"

- src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
- src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/file/File.java
- src/main/java/bdbe/bdbd/member/MemberRequest.java
- src/main/java/bdbe/bdbd/member/MemberRestController.java
- src/main/java/bdbe/bdbd/member/MemberService.java
- src/main/java/bdbe/bdbd/member/OwnerResponse.java
- src/main/java/bdbe/bdbd/member/OwnerRestController.java
- src/main/java/bdbe/bdbd/member/OwnerService.java
- src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
- src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
- src/main/java/bdbe/bdbd/reservation/ReservationService.java
- src/main/java/bdbe/bdbd/review/ReviewRequest.java
- src/main/java/bdbe/bdbd/review/ReviewRestController.java
- src/main/java/bdbe/bdbd/review/ReviewService.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
- src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
- src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
- src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
> refactor: 유저, owner 회원가입 리팩토링

- src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
- src/main/java/bdbe/bdbd/_core/errors/exception/ForbiddenError.java
- src/main/java/bdbe/bdbd/_core/errors/exception/UnAuthorizedError.java
- src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
- src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
- src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
- src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
- src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
- src/main/java/bdbe/bdbd/bay/BayRequest.java
- src/main/java/bdbe/bdbd/bay/BayRestController.java
- src/main/java/bdbe/bdbd/bay/BayService.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/file/File.java
- src/main/java/bdbe/bdbd/file/FileRequest.java
- src/main/java/bdbe/bdbd/file/FileResponse.java
- src/main/java/bdbe/bdbd/member/OwnerService.java
- src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
- src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
- src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
- src/main/java/bdbe/bdbd/reservation/ReservationService.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
- src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
- src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
변경 사항
- 예외 처리 핸들러 추가
- 토큰 만료 및 검증 실패 처리
- 예약 권한 로직 구현
- 삭제된 예약 조회 방지
- 동일 베이번호 예외 처리 및 유효성 검사
- 파일 관련 코드 정리: 사용되지 않는 `path` 필드를 주석 처리
> feat: 기능 개선 및 예외처리

- src/main/java/bdbe/bdbd/member/OwnerResponse.java
- src/main/java/bdbe/bdbd/member/OwnerService.java
- src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
- 예약 내역 조회 시, 현재 시간을 기준으로 carashId를 요청하도록 코드를 개선했습니다. 
- 세차장별 매장관리 기능에 이번달 매출 및 이번달 예약 내역을 요청하도록 코드를 개선했습니다.
> refactor:기능 개선 및 버그 수정을 위한 코드 리팩토링

- src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/file/FileJPARepository.java
- src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
- src/main/java/bdbe/bdbd/member/OwnerResponse.java
- src/main/java/bdbe/bdbd/member/OwnerService.java
- src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
- 삭제된 파일이 여전히 보이는 문제를 DTO를 업데이트하여 해결했습니다. (커밋: `fix: 삭제된 파일은 안보이게끔 DTO 수정`)
- 파일 처리를 업데이트하여 업로드 중에 덮어쓰기를 방지하기 위해 유일한 파일 이름으로 UUID를 사용하도록 했습니다. (커밋: `feat: UUID를 통해 유일한 파일명을 가지도록 설정하여 업로드시 덮어쓰기 해결`)
- 세차장 상세 정보를 수정할 때 이미지 업데이트를 활성화했습니다. (커밋: `feat: 세차장 수정시 수정 이미지로 반영`)
- 세차장 등록 및 수정에 테스트 이미지와 키워드를 반영했습니다. (커밋: `fix: 세차장 등록, 수정 테스트 이미지 및 키워드 반영`)
- 코드 병합 충돌을 해결했습니다. (커밋: `fix: 코드 병합 충돌 해결`)
> feat: 파일 업로드 및 세차장 상세 관리 기능 업데이트 및 수정

- src/main/java/bdbe/bdbd/bay/BayRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
- src/main/java/bdbe/bdbd/file/FileRequest.java
- src/main/java/bdbe/bdbd/member/MemberRequest.java
- src/main/java/bdbe/bdbd/pay/PayController.java
- src/main/java/bdbe/bdbd/pay/PayRequest.java
- src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
- src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
- src/main/java/bdbe/bdbd/review/ReviewRequest.java
- src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
- CarwashRequest, FileRequest, PayRequest, ReservationRequest, ReviewRequest DTO 클래스에 유효성 검사 어노테이션을 추가하여 데이터의 정확성을 보다 철저히 검증
- 유효성 검사 실패 시 제공되는 에러 메시지를 영문으로 통일하여, 에러의 원인을 사용자에게 보다 명확하게 전달
- 데이터의 안정성 및 신뢰성 향상: 유효하지 않은 데이터가 시스템 내부로 전달되는 것을 효과적으로 차단
> refactor:  DTO 유효성 검증 강화 및 에러 메세지 일관성 개선

- src/main/java/bdbe/bdbd/bay/BayRequest.java
- src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/file/FileRequest.java
- src/main/java/bdbe/bdbd/member/MemberRequest.java
- src/main/java/bdbe/bdbd/pay/PayRequest.java
- src/main/java/bdbe/bdbd/pay/PayResponse.java
- src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
- src/main/java/bdbe/bdbd/review/ReviewRequest.java
- 코드 삭제: 사용되지 않는 변수들이 제거되었습니다. 이로 인해 코드의 복잡성이 감소하고, 유지보수가 용이해졌습니다.
- 유효성 검증 리팩토링: DTO 내부의 유효성 검증 로직을 개선하여 보다 명확하고 간결한 구조를 갖도록 변경하였습니다. 이는 향후 유효성 검증 규칙이 변경되거나 추가될 때 빠른 수정을 가능하게 합니다.
> refactor: 코드 정리 및 유효성 검증 로직 리팩토링

- src/main/java/bdbe/bdbd/_core/exception/ApiException.java
- src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
- src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
- src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
- src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
- src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
- src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
- src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
- src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
- src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
- src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
- src/main/java/bdbe/bdbd/_core/utils/FileUploadUtil.java
- src/main/java/bdbe/bdbd/_core/utils/FilterResponseUtils.java
- src/main/java/bdbe/bdbd/controller/common/CommonMemberController.java
- src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
- src/main/java/bdbe/bdbd/controller/open/OpenMemberController.java
- src/main/java/bdbe/bdbd/model/Code.java
- src/main/java/bdbe/bdbd/model/location/Location.java
- src/main/java/bdbe/bdbd/service/bay/BayService.java
- src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/service/file/FileService.java
- src/main/java/bdbe/bdbd/service/member/OwnerService.java
- src/main/java/bdbe/bdbd/service/member/UserService.java
- src/main/java/bdbe/bdbd/service/pay/PayService.java
- src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
서비스 레이어 전반에 걸친 예외 처리 로직을 전면 수정하여 일관된 에러 응답 구조를 제공하도록 수정했습니다. 맞춤형 예외 클래스를 도입하고 GlobalExceptionHandler에서 로직을 중앙집중화했습니다.
변경 사항
에러 코드를 통한 관리를 위해 새로운 맞춤형 예외 클래스와 연관된 ErrorCode 열거형을 도입했습니다.
일반적인 예외 대신 맞춤형 예외를 던지도록 서비스 메소드를 업데이트하여 에러 처리의 가독성과 유지보수성을 향상시켰습니다.
GlobalExceptionHandler를 수정하여 맞춤형 예외를 처리하고 이를 표준화된 ApiResult JSON 응답으로 변환합니다.
클라이언트가 일관된 에러 응답 형식을 받게 되어서, 프론트엔드가 클라이언트 측의 에러 처리를 구현하는 것을 쉽게 만들것입니다.
백엔드 개발자는 더 명확하고 유지보수가 용이한 에러 처리 구조의 혜택을 받게 될 것 같습니다.
> feat: 에러코드 정의서 반영을 위한 익셉션 구조 수정 및 기존 코드 수정

- src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
- src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
- src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
- 이미지 필수 옵션으로 변경
- 파일 업로드 실패 예외 처리
- 빈 파일 업로드 예외 처리
- 세차장 수정 시 키워드 검증 코드 추가
> feat: 세차장 관련 기능 개선 및 예외 처리 추가

- src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
- src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
- src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
- src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
- src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
- src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
- src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
- src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
메시지 json 형식이 기대되는 값에 맞추어 정상 반환하도록 변경하였고,
ApiException관련 없이 답변 일관성 추가하여 DTO 검증에서도 일관성 있는 답변을 받을 수 있습니다
> fix: 메시지 json 형식 정상 반환 및 ApiException관련 없이 답변 일관성 추가

- src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
- src/main/resources/application-prod.yml
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
> fix: 배포 주소 변경 및 dto 이름 변경

- src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
- src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
- src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
- src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Reverts Step3-kakao-tech-campus/Team10_BE#279
> Revert "fix: 변수명 변경"
